title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jaume-av.github.io/ADD24/

aux_links:
  Template Repository: https://aules.edu.gva.es/fp/course/view.php?id=138358


# Configuració de la navegació
nav:
  - title: Inici
    url: /
  - title: Serialització
    url: /fitxers/serialitzacio/