title: Streams
description: Streams i Fitxers a Java
theme: just-the-docs

url: https://jaume-av.github.io/ADD24/

aux_links:
  "Accés a Aules":
    - https://aules.edu.gva.es/fp/course/view.php?id=138358


