title: ACCÉS A DADES - 2n DAM
description: Accés a Dades - IES Benigasló
theme: just-the-docs

url: https://jaume-av.github.io/ADA/

aux_links:
  "Accés a Aules":
    - https://aules.edu.gva.es/fp/course/view.php?id=138358

search_enabled: true

footer:
  copyright: "© 2024 El Meu Projecte"
  links:
    - title: "Llicència CC BY-SA 4.0"
      url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Navegació directa sense desplegables
collections:
  docs:
    output: true
    permalink: /:path/
