title: AAD24
description: Streams i Fitxers a Java
theme: just-the-docs

url: https://jaume-av.github.io/ADD24/

aux_links:
  "Accés a Aules":
    - https://aules.edu.gva.es/fp/course/view.php?id=138358

search_enabled: true

footer:
  copyright: "© 2024 El Meu Projecte"
  links:
    - title: "Llicència CC BY-SA 4.0"
      url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Configuració de la barra de navegació
collections:
  docs:
    output: true
    permalink: /:path/

# Definició de l'ordre de navegació
nav_order: 1

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: "default"
      nav_order: 1
